home/urls.py
from django.urls import path
from home import views
from home.views import ProductReviewView, contact, add_to_favorites, remove_from_favorites

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='home_page'),
    path('about_us/', views.AboutUsTemplateView.as_view(), name='about_us'),
    path('contact/', contact, name='contact'),
    path('faq/', views.FAQ.as_view(), name='faq'),
    path('manage_categories/', views.CategoryListView.as_view(), name='manage_categories'),
    path('list_products/', views.ProductListView.as_view(), name='list-products'),
    path('create_product/', views.ProductCreateView.as_view(), name='create-product'),
    path('update_product/<int:pk>/', views.ProductUpdateView.as_view(), name='update-product'),
    path('delete_product/<int:pk>/', views.ProductDeleteView.as_view(), name='delete-product'),
    path('product_details/<int:pk>/', views.ProductDetailView.as_view(), name='product-details'),
    path('create_category/', views.CategoryCreateView.as_view(), name='create-category'),
    path('update_category/<int:pk>/', views.CategoryUpdateView.as_view(), name='category-update'),
    path('delete_category/<int:pk>/', views.CategoryDeleteView.as_view(), name='delete-category'),
    path('category/<str:category_slug>/', views.product_category_search, name='product_category_search'),
    path('product_review/', ProductReviewView.as_view(), name='product_review'),
    path('update_review/<int:pk>', views.ProductReviewUpdateView.as_view(), name='update-review'),
    path('delete_review/<int:pk>', views.ProductReviewDeleteView.as_view(), name='delete-review'),
    path('cart/', views.cart_view, name='cart'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('update_cart_item/', views.update_cart_item, name='update_cart_item'),
    path('remove_from_cart/', views.remove_from_cart, name='remove_from_cart'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
    path('add_favorite/<int:product_id>/', add_to_favorites, name='add_favorite'),
    path('remove_favorite/<int:product_id>/', remove_from_favorites, name='remove_favorite'),
    path('list_of_favorites/', views.FavoriteListView.as_view(), name='list_of_favorites'),
    path('thank_you/', views.thank_you, name='thank_you'),
    path('checkout/', views.checkout, name='checkout'),
]

vic_shop/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from userextend.forms import AuthenticationNewForm

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path('', include('userextend.urls')),
    path("login/", views.LoginView.as_view(form_class=AuthenticationNewForm), name="login"),
    path('', include('django.contrib.auth.urls')),

]

home/models.py
import uuid
from django.contrib.auth.models import AbstractUser
from django.db import models


# User
class SiteUser(AbstractUser):
    phone_number = models.CharField(max_length=11)
    address = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=150, blank=True)

    def __str__(self):
        return self.username

    # Category


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)  # cod unic de identificare atasat url-ului specific categoriei

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['name']

    def __str__(self):
        return self.name

    # Product


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    created_by = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='static/home/products/')
    slug = models.SlugField(max_length=20, unique=True)  # cod unic de identificare atasat url-ului specific produsului
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discounted_price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)  # ordonam produsele incepand cu cel mai nou adaugat in bd

    def __str__(self):
        return self.name

    def is_favorite(self, user):
        return self.favorites.filter(user=user).exists()

    # Favorite Product


class Favorite(models.Model):
    user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='favorites')
    added_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'product')

    # Product Reviews


class ProductReview(models.Model):
    user = models.ForeignKey(SiteUser, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, related_name="reviews")
    comment = models.TextField()
    rating_choices = [(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')]
    rating = models.PositiveIntegerField(choices=rating_choices, default=5)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Product Reviews'
        ordering = ['-created_on']

    def __str__(self):
        user_name = self.user.get_full_name() if self.user else "Anonymous"
        return 'Comment on {} by {}'.format(self.product, user_name)

    def get_rating(self):
        return self.rating

    # Contact


class Contact(models.Model):
    subject = models.CharField(max_length=255)
    message = models.TextField()
    email = models.EmailField()
    phone_number = models.CharField(max_length=11)

    def __str__(self):
        return self.subject


# Cart

class Cart(models.Model):
    STATUS = [
        ('open', 'Open'),
        ('closed', 'Closed'),
    ]
    user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS, default='open')

    def get_total_price(self):
        return sum(item.quantity * item.product.price for item in self.cartitem_set.all())


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'{self.quantity} x {self.product.name}'


class Order(models.Model):
    user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    order_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

    def __str__(self):
        return f'Order {self.order_id}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'{self.quantity} x {self.product.name}'

products/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from django.core.validators import MaxLengthValidator
from django.forms import TextInput, EmailInput, Select, NumberInput, Textarea

from home.models import Product, Category, ProductReview, Contact, SiteUser


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ['created_by']

        widgets = {
            'name': TextInput(
                attrs={'class': 'form-control', 'placeholder': "Please enter product name"}),
            'category': Select(
                attrs={'class': 'form-select'}),
            'description': Textarea(
                attrs={'class': 'form-control', 'placeholder': "Please enter product description", 'rows': 10}),
            # You can change the number of rows as needed
            'price': NumberInput(
                attrs={'class': 'form-control', 'placeholder': "Please enter product price (in RON)"}),
        }


class ProductUpdateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

        widgets = {
            'name': TextInput(
                attrs={'class': 'form-control', 'placeholder': "Please enter product name"}),
            'category': Select(
                attrs={'class': 'form-select'}),
            'description': TextInput(
                attrs={'class': 'form-control', 'placeholder': "Please enter product description"}),
            'price': NumberInput(
                attrs={'class': 'form-control', 'placeholder': "Please enter product price"}),
        }


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

        widgets = {
            'name': TextInput(
                attrs={'class': 'form-control', 'placeholder': "Please enter product category name"}),
            'slug': TextInput(
                attrs={'class': 'form-select', 'placeholder': "Please enter product category slug"})
        }


class ContactForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

    class Meta:
        model = Contact
        fields = ['subject', 'message', 'email', 'phone_number']
        widgets = {
            'subject': forms.TextInput(attrs={'placeholder': 'Subject'}),
            'message': forms.Textarea(attrs={'placeholder': 'Your message...'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Your Email'}),
            'phone_number': forms.TextInput(attrs={'placeholder': 'Your Phone Number'}),
        }


class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = ProductReview
        fields = ['comment', 'rating', 'product']
        widgets = {
            'product': forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['comment'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Enter your comment'})
        self.fields['rating'].widget.attrs.update({'class': 'form-control'})


class ConfirmationForm(forms.ModelForm):
    phone_number = forms.CharField(validators=[MaxLengthValidator(11)])

    class Meta:
        model = SiteUser
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'address', 'city']

templates/product/cart.html
{% extends 'base.html' %}

{% block title %}Your Cart{% endblock %}

{% block content %}
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-lg-10">
                <div class="card border-0 shadow">
                    <div class="card-header bg-dark-blue text-white">
                        <h4 class="text-center mb-0">Shopping Cart</h4>
                    </div>
                    <ul class="list-group list-group-flush">
                        {% for cart_item in cart.cartitem_set.all %}
                            <li class="list-group-item">
                                <div class="row align-items-center">
                                    <div class="col-md-2">
                                        <img src="{{ cart_item.product.image.url }}" alt="{{ cart_item.product.name }}" class="img-fluid rounded">
                                    </div>
                                    <div class="col-md-4">
                                        <h5 class="card-title">{{ cart_item.product.name }}</h5>
                                        <h6 class="card-title" style="color: orangered;">{{ cart_item.product.price }} RON</h6>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="d-flex justify-content-end align-items-center">
                                            <form action="{% url 'update_cart_item' %}" method="post" class="form-inline">
                                                {% csrf_token %}
                                                <input type="hidden" name="product_id" value="{{ cart_item.product.id }}">
                                                <input type="hidden" name="quantity_change" value="-1">
                                                <button type="submit" class="btn btn-outline-danger btn-sm me-2">-</button>
                                            </form>
                                            <span class="badge bg-secondary">{{ cart_item.quantity }}</span>
                                            <form action="{% url 'update_cart_item' %}" method="post" class="form-inline">
                                                {% csrf_token %}
                                                <input type="hidden" name="product_id" value="{{ cart_item.product.id }}">
                                                <input type="hidden" name="quantity_change" value="1">
                                                <button type="submit" class="btn btn-outline-success btn-sm ms-2">+</button>
                                            </form>
                                            <form action="{% url 'remove_from_cart' %}" method="post" class="form-inline ms-4">
                                                {% csrf_token %}
                                                <input type="hidden" name="product_id" value="{{ cart_item.product.id }}">
                                                <button type="submit" class="btn btn-outline-danger btn-sm">Remove</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        {% empty %}
                            <li class="list-group-item text-center">Your cart is empty.</li>
                        {% endfor %}
                    </ul>
                    <div class="card-footer bg-white">
                        <div class="text-center">
                            <h5 class="mb-3 text-crimson">Total: {{ total_price }} RON</h5>
                            <a href="{% url 'list-products' %}" class="btn btn-outline-primary btn-sm">Continue Shopping</a>
                            <form action="{% url 'clear_cart' %}" method="post" class="d-inline">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-outline-danger btn-sm">Clear Cart</button>
                            </form>
                            <form action="{% url 'checkout' %}" method="post" class="d-inline">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-outline-success btn-sm">Checkout</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/product/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Checkout {% endblock %}

{% block content %}

    <div id="unique-checkout-page">
        <div class="unique-checkout-card">
            <div class="unique-checkout-header">
                <h3>Confirm your order contact details:</h3>
            </div>
            <form method="post" action="{% url 'checkout' %}" class="unique-checkout-form">
                {% csrf_token %}
                <h4>Your current account's contact details:</h4>
                <p>First Name: {{ user.first_name }}</p>
                <p>Last Name: {{ user.last_name }}</p>
                <p>Email: {{ user.email }}</p>
                <p>Phone Number: {{ user.phone_number }}</p>
                <p>Address: {{ user.address }}</p>
                <p>City: {{ user.city }}</p>

                <h4>Your contact details for this order:</h4>
                <div class="form-group">
                    <label>{{ form.first_name.label }}</label>
                    <input type="text" name="first_name" value="{{ user.first_name }}" class="form-control"
                           id="id_first_name">
                </div>
                <div class="form-group">
                    <label>{{ form.last_name.label }}</label>
                    <input type="text" name="last_name" value="{{ user.last_name }}" class="form-control"
                           id="id_last_name">
                </div>
                <div class="form-group">
                    <label>{{ form.email.label }}</label>
                    <input type="email" name="email" value="{{ user.email }}" class="form-control"
                           id="id_email">
                </div>
                <div class="form-group">
                    <label>{{ form.phone_number.label }}</label>
                    <input type="text" name="phone_number" value="{{ user.phone_number }}"
                           class="form-control"
                           id="id_phone_number" maxlength="11">
                </div>
                <div class="form-group">
                    <label>{{ form.address.label }}</label>
                    <input type="text" name="address" value="{{ user.address }}" class="form-control"
                           id="id_address">
                </div>
                <div class="form-group">
                    <label>{{ form.city.label }}</label>
                    <input type="text" name="city" value="{{ user.city }}" class="form-control"
                           id="id_city">
                </div>
                <br>
                <button type="submit" class="unique-checkout-btn unique-checkout-btn-confirm">Confirm Purchase</button>
                <a href="{% url 'list-products' %}" class="unique-checkout-btn unique-checkout-btn-danger">Cancel</a>
            </form>
        </div>
    </div>

{% endblock %}

templates/product/create_category.html
{% extends 'base.html' %}
{% block title %}Create a new category{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <br><br>
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Create a product category</h3>
                    </div>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn-custom-green">Add Category</button>
                            <a href="{% url 'manage_categories' %}" class="btn-custom-red">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/product/list_of_products.html
{% extends 'base.html' %}
{% load static %}
{% block title %} List of products{% endblock %}

{% block content %}
    <style>
        legend {
            font-size: 1rem !important;
        }
    </style>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 gy-5">
                <div class="card shadow-sm">
                    <div class="card-header text-white" style="background-color: #303030;">
                        <h3 class="text-center">Filters</h3>
                    </div>
                    <form method="get">
                        <div class="card-body">
                            {{ filters }}
                        </div>
                        <div class="card-footer text-center bg-light">
                            <button type="submit" class="btn btn-success">Search</button>
                            <a href="{% url 'list-products' %}" class="btn btn-danger">Reset</a>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-10 mb-5">
                <div class="row">
                    {% if all_products %}
                        {% for product in all_products %}
                            <div class="col-md-2 gy-5">
                                <div class="card">
                                    {% if product.image %}
                                        <img class="card-img-top" src="{{ product.image.url }}"
                                             alt="Product image"
                                             height="300">
                                    {% else %}
                                        <img class="card-img-top" src="{% static 'images/image-not-found.jpg' %}"
                                             alt="Product not found image" height="300">
                                    {% endif %}
                                    <div style="overflow-y: hidden; height: 300px">
                                        <div class="card-body">
                                            <h5 class="card-title">{{ product.name }}</h5>
                                            <br>
                                            <ul class="list-group list-group-flush">
                                                <li class="list-group-item">
                                                    <div class="average-rating" style="display: flex; justify-content: space-between; align-items: center;">
                                                        <span title="{{ product.formatted_average_rating }}/5">
                                                            {% if product.average_rating == 0 or product.average_rating is none %}
                                                                {% for i in "12345" %}
                                                                    <i class="bi bi-star"></i>
                                                                {% endfor %} (No reviews yet)
{#                                                                <i class="bi bi-star"></i> <i class="bi bi-star"></i> <i class="bi bi-star"></i> <i class="bi bi-star"></i> <i class="bi bi-star"></i> (No reviews yet)#}
                                                            {% else %}
                                                                {% for i in "12345" %}
                                                                    {% if forloop.counter <= product.full_stars %}
                                                                        <i class="bi bi-star-fill"></i>
                                                                    {% elif forloop.counter == product.full_stars|add:"1" and product.half_star %}
                                                                        <i class="bi bi-star-half"></i>
                                                                    {% else %}
                                                                        <i class="bi bi-star"></i>
                                                                    {% endif %}
                                                                {% endfor %}
                                                            {% endif %}
                                                        </span>
                                                        {% if request.user.is_authenticated %}
                                                            <div>
                                                                {% if product.favorite %}
                                                                    <a href="{{ product.remove_favorite_url }}"><i class="bi bi-heart-fill" title="Remove From Favorites"></i></a>
                                                                {% else %}
                                                                    <a href="{{ product.add_favorite_url }}"><i class="bi bi-heart" title="Add To Favorites"></i></a>
                                                                {% endif %}
                                                            </div>
                                                        {% endif %}
                                                    </div>
                                                </li>
                                                <li class="list-group-item"> Category: {{ product.category }}</li>
                                                <li class="list-group-item" style="font-size: 16px; font-weight: bold; color: orangered">
                                                    Price: {{ product.price }} RON
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div>
                                        <div class="card-footer d-flex justify-content-center">
                                            <div class="row">
                                                <div class="col text-center">
                                                    <a class="btn btn-danger mt-1"
                                                       href="{% url 'product-details' product.id %}"
                                                       style="font-size: 22px; padding: 1px 18px" title="Product Details"><i class="bi bi-clipboard-data"></i></a>
                                                </div>
                                                <div class="col text-center">
                                                    <form action="{% url 'add_to_cart' %}" method="post">
                                                        {% csrf_token %}
                                                        <input type="hidden" name="product_id" value="{{ product.id }}">
                                                        <input type="hidden" name="quantity" value="1">
                                                        <button type="submit" class="btn btn-success mt-1"
                                                                style="font-size: 22px; padding: 1px 18px" title="Add to Cart"><i
                                                                class="bi bi-cart-plus"></i></button>
                                                    </form>
                                                </div>
                                                {% if request.user.is_authenticated %}
                                                    {% if perms.home.change_product or perms.home.delete_product %}
                                                        <div class="col text-center">
                                                            <div class="dropdown">
                                                                <button class="btn btn-primary dropdown-toggle mt-1"
                                                                        type="button"
                                                                        data-bs-toggle="dropdown" aria-expanded="false"
                                                                        style="font-size: 22px; padding: 1px 10px" title="Edit">
                                                                    <i class="bi bi-pencil-square"></i>
                                                                </button>
                                                                <ul class="dropdown-menu">
                                                                    {% if perms.home.change_product %}
                                                                        <li><a class="dropdown-item"
                                                                               href="{% url 'update-product' product.id %}">Update</a>
                                                                        </li>
                                                                    {% endif %}
                                                                    {% if perms.home.delete_product %}
                                                                        <li><a class="dropdown-item"
                                                                               href="{% url 'delete-product' product.id %}">Delete</a>
                                                                        </li>
                                                                    {% endif %}
                                                                </ul>
                                                            </div>
                                                        </div>
                                                    {% endif %}
                                                {% endif %}
                                            </div>
                                        </div>
                                        <div style="text-align: center;">
                                            <small class="text-muted">Created
                                                on: {{ product.created|date:"d-m-Y H:i:s" }}</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        No data available.
                    {% endif %}

                    <div style="display: flex; justify-content: center; margin-top: 40px;">
                        <div class="pagination" style="background-color: #f5f5f5; padding: 10px; border-radius: 5px;">
                            <span class="step-links">
                                {% if page_obj.has_previous %}
                                    <a href="?page=1">&laquo; first</a>
                                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                                {% endif %}

                                <span class="current">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                </span>

                                {% if page_obj.has_next %}
                                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                                {% endif %}
                            </span>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    
{% endblock %}

templates/product/thank_you.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Thank You{% endblock %}

{% block content %}
    <div id="thank-you-page">
        <h2 class="thank-you-message">Thank You for Your Purchase!</h2>
        <p>More information regarding your purchase has been sent to your email.</p>
        <a href="{% url 'list-products' %}" class="btn-product-list">Back to Product List</a>
    </div>
{% endblock %}