home/urls.py
from django.urls import path
from home import views
from home.views import ProductReviewView, contact, add_to_favorites, remove_from_favorites

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='home_page'),
    path('about_us/', views.AboutUsTemplateView.as_view(), name='about_us'),
    path('contact/', contact, name='contact'),
    path('faq/', views.FAQ.as_view(), name='faq'),
    path('manage_categories/', views.CategoryListView.as_view(), name='manage_categories'),
    path('list_products/', views.ProductListView.as_view(), name='list-products'),
    path('create_product/', views.ProductCreateView.as_view(), name='create-product'),
    path('update_product/<int:pk>/', views.ProductUpdateView.as_view(), name='update-product'),
    path('delete_product/<int:pk>/', views.ProductDeleteView.as_view(), name='delete-product'),
    path('product_details/<int:pk>/', views.ProductDetailView.as_view(), name='product-details'),
    path('create_category/', views.CategoryCreateView.as_view(), name='create-category'),
    path('update_category/<int:pk>/', views.CategoryUpdateView.as_view(), name='category-update'),
    path('delete_category/<int:pk>/', views.CategoryDeleteView.as_view(), name='delete-category'),
    path('category/<str:category_slug>/', views.product_category_search, name='product_category_search'),
    path('product_review/', ProductReviewView.as_view(), name='product_review'),
    path('update_review/<int:pk>', views.ProductReviewUpdateView.as_view(), name='update-review'),
    path('delete_review/<int:pk>', views.ProductReviewDeleteView.as_view(), name='delete-review'),
    path('cart/', views.cart_view, name='cart'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('update_cart_item/', views.update_cart_item, name='update_cart_item'),
    path('remove_from_cart/', views.remove_from_cart, name='remove_from_cart'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
    path('add_favorite/<int:product_id>/', add_to_favorites, name='add_favorite'),
    path('remove_favorite/<int:product_id>/', remove_from_favorites, name='remove_favorite'),
    path('list_of_favorites/', views.FavoriteListView.as_view(), name='list_of_favorites'),
    path('thank_you/', views.thank_you, name='thank_you'),
    path('checkout/', views.checkout, name='checkout'),
]

vic_shop/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from userextend.forms import AuthenticationNewForm

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path('', include('userextend.urls')),
    path("login/", views.LoginView.as_view(form_class=AuthenticationNewForm), name="login"),
    path('', include('django.contrib.auth.urls')),

]

home/models.py
import uuid
from django.contrib.auth.models import AbstractUser
from django.db import models


# User
class SiteUser(AbstractUser):
    phone_number = models.CharField(max_length=11)
    address = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=150, blank=True)

    def __str__(self):
        return self.username

    # Category


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)  # cod unic de identificare atasat url-ului specific categoriei

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['name']

    def __str__(self):
        return self.name

    # Product


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    created_by = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='static/home/products/')
    slug = models.SlugField(max_length=20, unique=True)  # cod unic de identificare atasat url-ului specific produsului
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discounted_price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)  # ordonam produsele incepand cu cel mai nou adaugat in bd

    def __str__(self):
        return self.name

    def is_favorite(self, user):
        return self.favorites.filter(user=user).exists()

    # Favorite Product


class Favorite(models.Model):
    user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='favorites')
    added_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'product')

    # Product Reviews


class ProductReview(models.Model):
    user = models.ForeignKey(SiteUser, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, related_name="reviews")
    comment = models.TextField()
    rating_choices = [(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')]
    rating = models.PositiveIntegerField(choices=rating_choices, default=5)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Product Reviews'
        ordering = ['-created_on']

    def __str__(self):
        user_name = self.user.get_full_name() if self.user else "Anonymous"
        return 'Comment on {} by {}'.format(self.product, user_name)

    def get_rating(self):
        return self.rating

    # Contact


class Contact(models.Model):
    subject = models.CharField(max_length=255)
    message = models.TextField()
    email = models.EmailField()
    phone_number = models.CharField(max_length=11)

    def __str__(self):
        return self.subject


# Cart

class Cart(models.Model):
    STATUS = [
        ('open', 'Open'),
        ('closed', 'Closed'),
    ]
    user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS, default='open')

    def get_total_price(self):
        return sum(item.quantity * item.product.price for item in self.cartitem_set.all())


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'{self.quantity} x {self.product.name}'


class Order(models.Model):
    user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    order_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

    def __str__(self):
        return f'Order {self.order_id}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'{self.quantity} x {self.product.name}'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href={% static 'css/my_style.css' %}>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}" />
</head>
<body>

{% include 'navbar.html' %}

{% block content %} {% endblock %}


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
<script src="{% static 'js/my_script.js' %}"></script>
</body>
</html>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg" style="background-color: #303030;">
    <div class="container">
        <!-- Logo -->
        <a class="navbar-brand" href="{% url 'home_page' %}" style="margin-right: 1rem;">
            <img src="{% static 'images/nv-shop-navbar.jpeg' %}" class="custom-navbar-image" alt="Home image">
        </a>
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
           <!-- Navbar links -->
        <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
            <ul class="navbar-nav" style="flex: 1;">
                <!-- Search Bar -->
                <li class="nav-searchbar" style="margin-left: 1rem; margin-right: 2rem; width: 50%;">
                    <form method="get" class="d-flex" role="search" action="{% url 'list-products' %}">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="name" style="width: 100%;">
                        <button class="btn btn-outline-light" type="submit">Search</button>
                    </form>
                </li>
                <!-- About Us Dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        About us
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'about_us' %}">Company</a></li>
                        <li><a class="dropdown-item" href="{% url 'contact' %}">Contact</a></li>
                        <li><a class="dropdown-item" href="{% url 'faq' %}">FAQ</a></li>
                    </ul>
                </li>
                <!-- Categories Dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Categories
                    </a>
                    <ul class="dropdown-menu">
                        {% for category in category_list %}
                        <li><a class="dropdown-item" href="{% url 'list-products' %}?category={{ category.id }}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <!-- Products Dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Products
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'list-products' %}">List of Products</a></li>
                        {% if perms.home.add_product %}
                            <li><a class="dropdown-item" href="{% url 'create-product' %}">Add New Product</a></li>
                        {% endif %}
                        {% if perms.home.view_category %}
                            <li><a class="dropdown-item" href="{% url 'manage_categories' %}">Manage Categories</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>



            <ul class="navbar-nav ms-auto d-flex align-items-center">
                <!-- Favorite Icon -->
                {% if user.is_authenticated %}
                <li class="nav-item" style="position: relative; top: 2px; margin-right: 20px;"> <!-- Adjust the right margin to create space -->
                    <a class="nav-link active" href="{% url 'list_of_favorites' %}" role="button">
                        <i class="bi bi-heart-fill" style="font-size: 1.5rem;"></i>
                    </a>
                </li>
                {% endif %}
                <!-- Cart Icon -->
                {% if user.is_authenticated %}
                <li class="nav-item" style="position: relative;">
                    <a class="nav-link active" href="{% url 'cart' %}" role="button">
                        {% if cart_item_count %}
                            <span class="badge rounded-pill bg-danger" style="position: absolute; top: 28px; right: 17px; transform: translate(-50%, -50%);">
                                {{ cart_item_count }}
                            </span>
                        {% endif %}
                        <i class="bi bi-cart-fill" style="color: green; font-size: 1.5rem;"></i>
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'login' %}" role="button">
                        <i class="bi bi-cart-fill" style="color: green; font-size: 1.5rem;"></i>
                    </a>
                </li>
                {% endif %}
                <!-- Account Dropdown -->
                <li class="nav-item dropdown">
                    {% if user.is_authenticated %}
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAccount" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Account
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownAccount">
                        <li><a href="{% url 'details_user' request.user.id %}" class="dropdown-item">User Profile</a></li>
                        <li>
                            <form action="{% url 'logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="dropdown-item">Logout, {{ user.first_name }} {{ user.last_name }}</button>
                            </form>
                        </li>
                    </ul>
                    {% else %}
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAccount" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Account
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownAccount">
                        <li><a href="{% url 'login' %}" class="dropdown-item">Login</a></li>
                        <li><a href="{% url 'create_user' %}" class="dropdown-item">Sign up</a></li>
                    </ul>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>